// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhfmbbuzuygxvjspnqma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZm1iYnV6dXlneHZqc3BucW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjUzNDksImV4cCI6MjA1OTQ0MTM0OX0.2eH6OSuhunXV29mpQBECkGO6uF8N3JddobStXCmdHgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);